---

- name: create ecs
  cloudformation:
    stack_name: "{{ env }}-{{ application_name }}-ecs-stack"
    state: present
    region: "{{ aws_region }}"
    template: "{{ ecs_cfn_template }}"
    aws_access_key: "{{ assumed_role.sts_creds.access_key if role_arn is defined | default(false) else omit }}"
    aws_secrey_key: "{{ assumed_role.sts_creds.secret_key if role_arn is defined | default(false) else omit }}"
    security_token:  "{{ assumed_role.sts_creds.session_token if role_arn is defined | default(false) else omit }}"
    template_parameters:
      ApplicationName : "{{ application_name }}"
      Environment: "{{ env }}"
      InstanceType: "{{ ecs.instance_type }}"
      KeyPair: "{{ ecs.key_pair }}"
      SecurityGroup: "{{ ecs.security_group | default('') }}"
      ClusterSize: "{{ ecs.cluster_size }}"
      Subnets: "{{ ecs.subnets }}"
      ClusterName: "{{ ecs.cluster_name }}"
      InstanceNameTag: "{{ ecs.instance_name_tag }}"
      VpcId: "{{ vpc_id }}"